\import Data.Maybe
\import Logic
\import Paths
\import Paths.Meta
\import hw01 (gcd)
\import lect07
\open Nat(+)

-- 1. Определите функцию swap несколькими способами.

-- При помощи \cowith и доступа к полям.
\func swap {A B : \Type} (p : Pair A B) : Pair B A \cowith
  | fst_ => p.snd_
  | snd_ => p.fst_

-- При помощи \new и паттерн матчинга.
\func swap' {A B : \Type} (p : Pair A B) : Pair B A \elim p
  | (a, b) => \new Pair {
    | fst_ => b
    | snd_ => a
  }

-- При помощи \new и доступа к полям.
\func swap'' {A B : \Type} (p : Pair A B) : Pair B A =>
  \new Pair {
    | fst_ => p.snd_
    | snd_ => p.fst_
  }

-- 2. Докажите, что swap (swap p) = p.

\func swap-involutive {A B : \Type} (p : Pair A B) : swap (swap p) = p => idp

-- 3. Докажите, что тип PosNat 0 пустой, а тип PosNat 1 нет.

\func zero-isNotPos (p : PosNat 0) : Empty => p.p

\func one-isPos : PosNat 1 =>
  \new PosNat {
    | p => ()
  }

-- 4. Определите \record, состоящий из пар взаимно простых натуральных чисел.
--    Определите тип, состоящий из натуральных чисел, взаимно простых с 60.

\record Coprime (a b : Nat) (p : gcd a b = 1)

\func Coprime60 => Coprime 60

-- 5. Закончите определение класса монад. Этот класс должен содержать все монадные законы и реализовывать все поля из класса функторов.

\class Monad \extends Functor
  | return {A : \Set} : A -> F A
  | \infixl 1 >>= {A B : \Set} : F A -> (A -> F B) -> F B
  | >>=-left-id {A B : \Set} (a : A) (f : A -> F B) : (return a >>= f) = f a
  | >>=-right-id {A : \Set} (m : F A) : (m >>= return) = m
  | >>=-assoc {A B C : \Set} (x : F A) (f : A -> F B) (g : B -> F C) : (x >>= f >>= g) = (x >>= (\lam a => f a >>= g))
  | fmap f => \lam x => x >>= (\lam a => return (f a))
  | fmap-id => >>=-right-id
  | fmap-comp f g x => rewrite (>>=-assoc x (\lam a => return (f a)) (\lam b => return (g b))) (pmap (>>= x) (inv (path (\lam i => \lam a => (>>=-left-id (f a) (\lam b => return (g b))) i))))


-- 6. Определите \instance Monad для Maybe.

\instance MaybeMonad : Monad Maybe
  | return => just
  | >>= a f => \case \elim a \with {
    | nothing => nothing
    | just x => f x
  }
  | >>=-left-id a f => idp
  | >>=-right-id  x => \case \elim x \with {
    | nothing => idp
    | just x => idp
  }
  | >>=-assoc x f g => \case \elim x \with {
    | nothing => idp
    | just x => idp
  }

-- 7. Определите \instance Monad для State и State'.

\record State (S A : \Type)
  | state : S -> \Sigma S A

\data State' (S A : \Type)
  | state' (S -> \Sigma S A)
